liberapay: https://liberapay.com/sadko4u/donate
custom: https://www.bountysource.com/teams/lsp-plugins
custom: https://paypal.me/sadko4u
custom: https://etherscan.io/address/0x079b24da78d78302cd3cfbb80c728cd554606cc6
